const PREFIX = 'WEATHER_GET_INFO_VIEW_';

export const COUNTRY_LABEL_1_CHANGE = `${PREFIX}COUNTRY_LABEL_1_CHANGE`;
export const COUNTRY_LABEL_2_CHANGE = `${PREFIX}COUNTRY_LABEL_2_CHANGE`;
export const COUNTRY_LABEL_3_CHANGE = `${PREFIX}COUNTRY_LABEL_3_CHANGE`;
export const COUNTRY_LABEL_4_CHANGE = `${PREFIX}COUNTRY_LABEL_4_CHANGE`;